### ISSUE TITLE
Extend for krvajalm.linter-gfortran fortran plugin

### ISSUE THREAD

**Issue by ipcamit** [ekibun/FortranBreaker#2]
Hi, Current Fortran Breaker works for gimly81 fortran extension. i find krvajalm.linter-gfortran more appropriate for my use (fortran language server and all). Can you shed a bit of light how to extend it? I can do it myself.
thank you

**Comment by starship863** [comment]
This is exactly a good proposal. I am also looking forward for this feature.

**Comment by starship863** [comment]
This seems to be rather easy. Simply modify the file package.json,
in the line 32, add the following languageIds:
`"FortranFreeForm", "fortran_fixed-form"`
then this extension will support gimly81 fortran extension.

**Comment by ktarbet** [comment]
Hi @starship863 .  I used your suggestion and that allowed breakpoints in older style FORTRAN, on Linux!  Thanks!    

@ekibun   would you like a pull request (PR) for this change?

```json

 "enableBreakpointsFor": {
                                        "languageIds": [
                                                "fortran",
                                                "FortranFreeForm", 
                                                "fortran_fixed-form",
                                                "fortran-modern"
                                        ]
                                }


```
